[package]
name = "zkramp"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = "2.6.4"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.14.0" }

[tool.fmt]
sort-module-level-items = true

[[target.starknet-contract]]
sierra = true
casm = true
